--liquibase formatted sql
--changeset ildar:1
create table coupon
(
    id            bigint generated by default as identity
        primary key,
    coupon_code   varchar(255),
    creation_time timestamp,
    name          varchar(255),
    update_time   timestamp
);

create table coupon_type
(
    id            bigint generated by default as identity
        primary key,
    creation_time timestamp,
    type          varchar(255),
    update_time   timestamp
);

create table product
(
    id            bigint generated by default as identity
        primary key,
    article       varchar(255),
    creation_time timestamp,
    name          varchar(255),
    price         numeric(19, 2),
    update_time   timestamp
);

--changeset ildar:2
insert into product (id, article, name, price) values (1, '1', 'IPhone', 100);
insert into coupon (id, coupon_code, name) values (1, 'P10', 'Sale');
commit;
